#!/usr/bin/perl

use warnings;
use strict;
use 5.12.0;

use Spreadsheet::ParseExcel;
use Spreadsheet::ParseExcel::Simple;
use Data::Dumper;

my $wb = $ARGV[0];
my $hv_name = "USNJXS";
my $vm_name = "USNJXV";

my $xls     = Spreadsheet::ParseExcel::Simple->read( $wb );
my ( $hw_ws, $net_ws )  = $xls->sheets(); 
my %hv_info;
my $hv_id;

# get the network info first, or we'll waste cycles
# iterating repeatedly

my %vm_info;

while ( $net_ws->has_data() ){

    # compile network info for the vm

    my @row = $net_ws->next_row();
    next until $row[0] =~ /$vm_name\d\d/;

    my $vm_id = $row[0];

    my $eth1_ip = $row[6];
    ( $eth1_ip ) = $eth1_ip =~ /(\d+\.\d+\.\d+\.\d+)/;

    $vm_info{ $vm_id } = {
                            eth0_vlan   => $row[3],
                            eth0_ip     => $row[4],
                            eth1_vlan   => $row[5],
                            eth1_ip     => $eth1_ip,
                        };

    print Dumper \%vm_info;
}
exit;
while ( $hw_ws->has_data() ){
    
    my @hw_row = $hw_ws->next_row();

    # check if this row has an XS definition

    if ( $hw_row[0] =~ /$hv_name\d\d/ ){
        $hv_id = $hw_row[0];
        next;
    }

    # next if we haven't found an XS yet
    # we only generate configs for client vms

    next if ! $hv_id;
   
    if ( $hw_row[1] =~ /$vm_name/ ){
        
        my $name    = $hw_row[1];
        my $cpu     = $hw_row[2];
        my $ram     = $hw_row[3];
 
        $hv_info{ $hv_id }{ $name } = {
                                name    => $name,
                                cpu     => $cpu,
                                ram     => $ram,
                             };
    }
}


